project: default
source:
  repoURL: 'https://github.com/nbglink/DevOpsUpskill-FinalProject.git'
  path: ./argocd-app-config/demo-app
  targetRevision: HEAD
destination:
  server: 'https://kubernetes.default.svc'
  namespace: demo-app
syncPolicy:
  automated:
    prune: true
  syncOptions:
    - CreateNamespace=true
    - PruneLast=true